### PR TITLE
Fix markdown syntax error.

### PR DESCRIPTION
**Pull request by MontyPan**

### CODE REVIEW

**Comment by jDramaix** [comment]
fixed ac2bf31b55b29350ecd90e1e5dbf13b7d1eca743
Thanks

**Comment by rluble** [comment]
Julien pointed to the wrong PR, the fix was actually 4afa2d1.

**Comment by MontyPan** [comment]
Strange, 4afa2d1 is later than this PR. #5 is the same situation.
You or the team wish the other folks just create issue instad of create PR? 
That's ok, say it straight.

**Comment by rluble** [comment]
We are still working on the flow to accept PRs from Github.  Because those were quite small typo fixes in the documentation, I fixed them internally and exported the commit. 

We will have the flow to properly accept Github PRs soon.

**Pull request closed without merging**
