### PR TITLE
Cleanup EOL and EOF whitespace

### PR DESCRIPTION
**Pull request by realityforge**
Ensure there is no trailing whitespace on a line and that files end with a new line.
This is mostly automated via using the zapwhite ruby gem available at

https://rubygems.org/gems/zapwhite

With the command line

> zapwhite --exclude-pattern '.*/output/.*' --exclude-pattern '.*\.java\.js\.txt' --exclude-pattern '.*_whitelist\.txt' --exclude-pattern '.*\.stacktrace\.txt'

### CODE REVIEW

**Comment by realityforge** [comment]
It should be noted that this also fixes the TravisCI build that was failing because of a lack of a new line at the end of the file in `.bazelrc`

**Comment by jDramaix** [comment]
Thanks for that cleanup.

**Comment by jDramaix** [comment]
After discussion with team, we will not import this patch as is. We don't have policy that enforce new line at the end of files. Nothing prevent to have the same in the future.
It seems it's more a bug in bazel and we will fill a bug report for that.
That being said, I'll add a new line to our .bazelrc in order to work around the bug.

**Comment by realityforge** [comment]
Sounds good

**Pull request closed without merging**
